//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstproject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrun
    {
        public int UrunID { get; set; }
        public string UrunAdı { get; set; }
        public int BirimID { get; set; }
        public Nullable<System.DateTime> UrunKayitTarih { get; set; }
        public int KayitBilgisiID { get; set; }
        public int UrunKodu { get; set; }
        public int UrunGrubuID { get; set; }
    
        public virtual TblBirim TblBirim { get; set; }
        public virtual TblKullanıcı TblKullanıcı { get; set; }
        public virtual TblUrunGrub TblUrunGrub { get; set; }
    }
}
